---
- hosts: 
  remote_user: root 
  become: yes
  tasks: 
        - name: Removendo o pacote do zabbix-agent ja instalado
          yum:
                  name: zabbix-agent
                  state: removed

        - name: Removendo o pacote do zabbix-release ja instalado
          yum:
                  name: zabbix-release
                  state: removed 
      
        - name: Removendo o repositorio do Zabbix ja instalado
          action: raw rm -f /etc/yum.repos.d/zabbix.repo

        - name: Baixando o novo repositorio do Zabbix na versao 4.0
          get_url:
                  url: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
                  dest: /tmp

        - name: Instalando o repositorio do Zabbix 4.0
          shell: rpm -ivh /tmp/zabbix-release-4.0-2.el7.noarch.rpm warn=false 

        - name: Atualizando os pacotes
          shell: yum update -y warn=false 

        - name: Instalando o zabbix-agent
          yum:
                  name: zabbix-agent
                  state: installed

        - name: Alterando os parametros do arquivo de conf do zabbix-agent
          action: raw sed -i "s/Hostname=Zabbix server/# Hostname=Zabbix server/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# EnableRemoteCommands=0/EnableRemoteCommands=1/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# LogRemoteCommands=0/LogRemoteCommands=1/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# DebugLevel=3/DebugLevel=3/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# ListenPort=10050/ListenPort=10050/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# HostnameItem=system.hostname/HostnameItem=system.hostname/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# HostMetadata=/HostMetadata=Linux Homologacao/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# RefreshActiveChecks=120/RefreshActiveChecks=120/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# BufferSend=5/BufferSend=5/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# BufferSize=100/BufferSize=100/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# MaxLinesPerSecond=20/MaxLinesPerSecond=20/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# Timeout=3/Timeout=30/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# AllowRoot=0/AllowRoot=0/g" /etc/zabbix/zabbix_agentd.conf ; sed -i "s/# User=zabbix/User=zabbix/g" /etc/zabbix/zabbix_agentd.conf

        - name: Iniciando o zabbix-agent e habilitando para iniciar no boot do servidor
          service:
                  name: zabbix-agent
                  state: started
                  enabled: yes
